name: Publish Docker image

on:
  push:
    branches: 
      - main

jobs:
  push_to_registry:
    name: Build, Test and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repo
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      # Step 3: Install dependencies for testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: |
          python UnitTest.py  # Menjalankan file UnitTest.py

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/flask-mahasiswa  # Nama image di Docker Hub
      
      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
